apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu-debug-a
  name: ubuntu-debug-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-debug-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ubuntu-debug-a
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command: ["/bin/sleep", "3650d"]
        resources: {}
        ports:
        - containerPort: 5000
      # serviceAccountName: ubuntu-debug-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-debug-service
  labels:
    service: ubuntu-debug-service
spec:
  type:
  selector:
    app: ubuntu-debug-a
  ports:
  - port: 5000
    targetPort: 5000
